## Methodolgy ##

1. mouse 0 -> mouse 150 -> pose -> touchpad
2. mouse 150 -> pose -> touchpad -> mouse 0
3. pose -> touchpad -> mouse 0 -> mouse 150

## Results

In [9]:
import pandas as pd

from pathlib import Path

base = Path("../data")

steering_files = list(base.glob("steering_law/*.csv"))

steering_dfs = []

for file in steering_files:

    df = pd.read_csv(file)

    df["condition"] = df["input_method"]
    df["duration"] = df["end_time"] - df["start_time"]

    df.loc[df["latency"] == 150, "condition"] = "mouse_latency_150"
    

    steering_dfs.append(df)

steering_data = pd.concat(steering_dfs, ignore_index=True)

In [10]:
steering_data

,iteration,pid,path_length,path_width,start_time,end_time,success,input_method,latency,condition,duration
0,1,2,1000,35,1782831312887,1782831314863,True,touchpad,0,touchpad,1976
1,1,2,800,90,1782831316031,1782831316497,True,touchpad,0,touchpad,466
2,1,2,800,35,1782831317558,1782831318863,True,touchpad,0,touchpad,1305
3,1,2,500,90,1782831319663,1782831320020,True,touchpad,0,touchpad,357
4,1,2,1000,70,1782831321014,1782831322196,True,touchpad,0,touchpad,1182
...,...,...,...,...,...,...,...,...,...,...,...
386,3,1,500,35,1782828835035,1782828837635,True,mouse,150,mouse_latency_150,2600
387,3,1,1000,90,1782828839451,1782828840585,True,mouse,150,mouse_latency_150,1134
388,3,1,500,70,1782828842752,1782828843501,True,mouse,150,mouse_latency_150,749
389,3,1,1000,35,1782828846650,1782828854784,True,mouse,150,mouse_latency_150,8134
390,3,1,800,35,1782828857801,1782828860801,True,mouse,150,mouse_latency_150,3000

In [11]:
fitts_files = list(base.glob("fitts_law/*.csv"))

fitts_dfs = []

for file in fitts_files:

    df = pd.read_csv(file)

    df["condition"] = df["input_method"]
    df["movement_time"] = df["timestamp"].diff()

    df.loc[df["latency"] == 150, "condition"] = "mouse_latency_150"

    fitts_dfs.append(df)

fitts_data = pd.concat(fitts_dfs, ignore_index=True)

In [13]:
fitts_data

,iteration,pid,num_targets,target_w,target_d,target_id,timestamp,input_method,latency,condition,movement_time
0,1,2,10,50,450,1,1782830583859,touchpad,0,touchpad,NaN
1,1,2,10,50,450,2,1782830584908,touchpad,0,touchpad,1049.0
2,1,2,10,50,450,3,1782830585807,touchpad,0,touchpad,899.0
3,1,2,10,50,450,4,1782830586742,touchpad,0,touchpad,935.0
4,1,2,10,50,450,5,1782830587424,touchpad,0,touchpad,682.0
...,...,...,...,...,...,...,...,...,...,...,...
3235,3,3,10,100,350,6,1782827704630,mouse,150,mouse_latency_150,821.0
3236,3,3,10,100,350,7,1782827705542,mouse,150,mouse_latency_150,912.0
3237,3,3,10,100,350,8,1782827706494,mouse,150,mouse_latency_150,952.0
3238,3,3,10,100,350,9,1782827707203,mouse,150,mouse_latency_150,709.0
3239,3,3,10,100,350,10,1782827708430,mouse,150,mouse_latency_150,1227.0

In [22]:
steering_summary = (
    steering_data
    .groupby("condition")
    .agg(
        mean_duration_ms=("duration", "mean"),
        std_duration_ms=("duration", "std"),
        success_rate=("success", "mean"),
        n=("duration", "count")
    )
    .reset_index()
)

# success rate in percent

steering_summary["success_rate"] = steering_summary["success_rate"] * 100

steering_summary = steering_summary.sort_values("mean_duration_ms")

steering_summary

           condition  mean_duration_ms  std_duration_ms  success_rate    n
3           touchpad       1567.602273      1318.430446     92.045455   88
0              mouse       1608.478723      1253.090157     86.170213   94
1  mouse_latency_150       2082.166667      1495.764885     90.000000   90
2               pose       2311.563025      1574.699873     68.067227  119

In [21]:
fitts_summary = (
    fitts_data
    .groupby("condition")
    .agg(
        mean_movement_time_ms=("movement_time", "mean"),
        std_movement_time_ms=("movement_time", "std"),  
        n=("movement_time", "count")
    )
    .reset_index()
)

fitts_summary = fitts_summary.sort_values(by="mean_movement_time_ms")
fitts_summary

           condition  mean_movement_time_ms  std_movement_time_ms    n
0              mouse             696.912020            284.313074  807
3           touchpad             761.390335            264.543401  807
1  mouse_latency_150            1044.146221            334.734324  807
2               pose            2713.904585           5322.212669  807

## Discussion

## Limitations & Problems